openapi: 3.0.0
info:
  title: Market Data API
  version: 'v3'
  x-logo:
    url: 'https://docs.bravenewcoin.com/images/logo.png'
    altText: 'Brave New Coin'
  contact:
    name: Brave New Coin
    url: 'https://bravenewcoin.com/'
    email: support@bravenewcoin.com
servers:
  - url: 'https://api.bravenewcoin.com/{basePath}'
    description: Production API Server
    variables:
      basePath:
        default: v3
components:
  securitySchemes:
    auth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://api.bravenewcoin.com/v3/oauth/token'
          scopes:
            read:asset: Read available assets
            read:market: Read available markets
            read:exchange: Read available exchanges
            read:exchange-ticker: Read exchange ticker
            read:index-ticker: Read index ticker
            read:ohlcv: Read end of day open, high, low, close and volume
            read:market-cap: Read the market capatilization
x-tagGroups:
  - name: General
    tags:
      - Overview
      - Authentication
      - Pagination
      - Timezones
      - Versioning
  - name: Websocket API
    tags:
      - Websocket Overview
      - Websocket Errors
      - Websocket Exchange Ticker
  - name: Beta Websocket API
    tags:
      - Websocket Index Ticker
  - name: Rest API
    tags:
      - Rest API Errors
      - Asset
      - Market
      - Exchange
      - Exchange Ticker
  - name: Beta Rest API
    tags:
      - Index Ticker
      - Open, High, Low, Close, Volumes
      - Market Cap
      - Taxonomy
tags:
  - name: Authentication
    description: |
      We use OAuth2 flows for security.

      ## Websocket API Authentication

      Our websocket endpoint requires the bearer token to be sent as *access_token* parameter in the connection url. The token will have to be used within 30 seconds of being issued.

      ```
      wss://ws.bravenewcoin.com?access_token=<token>
      ```

      ## Rest API Authentication

      Our REST endpoints require a valid bearer token to be sent in the Authorization header.
      ```
      Authorization: Bearer <token>
      ```
      <!-- ReDoc-Inject: <security-definitions> -->
  - name: Overview
    description: |
      Brave New Coin has been tracking crypto asset ticker data from the worlds major exchanges since April 2014. We now provide data from ~250 exchanges.

      The Brave New Coin github organisation has example API clients for your usage:
      * [Java](https://github.com/bnc-projects/java-api-client)
      * [JavaScript](https://github.com/bnc-projects/bnc-websocket-client-sample)

      If the language which you are working in isn't found in our list, then feel free to download the OpenAPI specification and generate your own clients in the language of your choice. The download link can be found at the top of this page; and is available on [github](https://github.com/bnc-projects/web-api).

      If you find any errors with our documentation, feel free to create issues and/or pull requests on [github](https://github.com/bnc-projects/web-api).

      ### Usage of our APIs
      We recommend using UUIDs to access data from this API. The following resources are our informational API that can be queried to provide UUIDs:
      * [Asset](#tag/Asset)
      * [Market](#tag/Market)
      * [Exchange](#tag/Exchange)

  - name: Websocket Overview
    description: |
      Brave New Coin Websocket API exposes exchange ticker data via Websockets. Clients need to send subscribe message to start recieving data. See [Exchange Ticker](#tag/Websocket-Exchange-Ticker).

      A sample project using the BNC Websocket API is available on Github :

      * [Node.js](https://github.com/bnc-projects/bnc-websocket-client-sample)

      ### Connection URL

      `wss://ws.bravenewcoin.com?access_token=<token>`

      ### Authentication

      All websocket connections require authentication. For more information see -

      * [Authentication](#tag/Authentication)

      ### Common Message Types

      Websocket messages have an `event` field to identify them

      #### Connection Message

      Once the client connection is successful, the server will send back a connection message
      ```
      {
        "event" : "CONNECTED",
        "timestamp" : "2018-09-05T01:34:39Z"
      }
      ```

      #### Ping message

      Clients or server can send a ping request to check if the connection is active. Clients are expected to implement a `pong` response. The server may terminate the connection if the client does not respond to `ping` from the server.

      Request
      ```
      {
        "event": "PING"
      }
      ```
      Response
      ```
      {
        "event": "PONG",
        "timestamp": "2018-09-05T01:34:39Z"
      }
      ```
  - name: Websocket Errors
    description: |
      Server will return an error message in the below format
      ```
      {
        "event": "ERROR",
        "code": "400",
        "message": "Invalid event type provided",
        "timestamp": "2018-09-05T01:34:39Z"
      }
      ```
      ### Error code summary

      Error Code                         | Description
      -----------------------------------|------------
      400 - Bad Request                  | The request was unacceptable, often due to missing a required parameter.
      401 - Unauthorized                 | No valid OAuth2 token provided
      403 - Forbidden                    | Not authorized to access this resource
      (please contact sales about adding access to your profile).
      404 - Not Found                    | Requested resource not found(typically the marketId or exchangeId passed through the subscription request not found)

      There may be other types of errors that may be returned and we recommend handling the ERROR type gracefully.
  - name: Websocket Exchange Ticker
    description: |

      This endpoint can be used to subscribe to the raw ticker data from different exchanges. Clients can send a Subscribe message to start receiving.



      To subscribe to all the ticks of an exchange only the exchangeId can be sent. To subscribe to all the ticks of an market only the marketId or marketName can be sent. Both exchangeId and marketId can be sent to subscribe to the market in an exchange. Clients can subscribe to multiple sources as required. Clients need to call the [Market](#tag/Market) and [Exchange](#tag/Exchange) REST API's to get the ids.

      ### Parameters

      Name                      | Description
      --------------------------|------------
      marketId                  | Subscribe to the exchange ticks for this market
      exchangId                 | Subscribe to the exchange ticks for this exchange
      marketName                | Subscribe to the exchange ticks for this exchange by the trade pair. e.g. BTC_USD. It is recommended to subscribe by the marketId rather than the marketName

      #### Subscribe to Exchange

      ```
      {
        "event": "SUBSCRIBE_EXCHANGE_TICKER",
        "exchangeId": "359107d3-bd1a-418c-9470-58831ed9a45e"
      }
      ```

      #### Subscribe to Market by Id

      ```
      {
        "event": "SUBSCRIBE_EXCHANGE_TICKER",
        "marketId": "359107d3-bd1a-418c-9470-58831ed9a45e"
      }
      ```
      #### Subscribe to Market by Name

      ```
      {
        "event": "SUBSCRIBE_EXCHANGE_TICKER",
        "marketName": "BTC_USD"
      }
      ```
      #### Subscribe to a Market in an Exchange

      ```
      {
        "event": "SUBSCRIBE_EXCHANGE_TICKER",
        "exchangeId": "359107d3-bd1a-418c-9470-58831ed9a45e"
        "marketId": "f7cbc588-283e-41da-9c28-eee2113d7b8d"
      }
      ```
      #### Response

      The server will return ticks in this format
      ```
      {
        "event": "EXCHANGE_TICKER"
        "id": "string",
        "exchangeId": "string",
        "marketId": "string",
        "last": "string",
        "volume": "string",
        "bid": "string",
        "ask": "string",
        "timestamp": "2018-09-06T04:35:44Z"
      }
      ```
    x-traitTag: true
  - name: Websocket Index Ticker
    description: |

      This endpoint can be used to subscribe to the index ticker data. These indices are calculated by BNC and published to the websocket endpoint. Clients need to send a Subscribe message to start receiving.
      Indices can be subscribed by the indexId or the indexType.

      The index id will differ based on the index type.

      | Index Type | Index Id  |
      | -----------|:---------:|
      | MWA        |Market Id  |
      | GWA        |Asset Id   |

      Clients need to call the [Market](#tag/Market) and [Asset](#tag/Asset) REST API's to get the ids.

      #### Subscribe by Index ID

      ```
      {
        "event": "SUBSCRIBE_INDEX_TICKER",
        "indexId": "359107d3-bd1a-418c-9470-58831ed9a45e"
      }
      ```

      #### Subscribe by Index Type

      ```
      {
        "event": "SUBSCRIBE_INDEX_TICKER",
        "indexType": "MWA"
      }
      ```

      #### Response

      The server will return ticks in this format
      ```
      {
        "event": "INDEX_TICKER"
        "id": "string",
        "indexId": "string",
        "indexType": "string",
        "price": "string",
        "volume": "string",
        "timestamp": "2018-09-06T04:35:44Z"
      }
      ```
    x-traitTag: true
  - name: Rest API Errors
    description: |
      Brave New Coin uses conventional HTTP response codes to indicate the success or failure of an API request. In general: Codes in the `2xx` range indicate success. Codes in the `4xx` range indicate an error that failed given the information provided (e.g. A  required parameter was missing). Codes in the `5xx` range indicate an error with Brave New Coin's servers.

      Some `4xx` errors that could be handled programmatically include an error code that briefly explains the error reported.
      ```
      {
        "status": "BAD_REQUEST",
        "timestamp": "2018-08-14T21:55:46.055Z",
        "message": "validation error",
        "errors": [
          {
            "object": "Asset",
            "field": "status",
            "rejectedValue": "ERROR",
            "message": "Invalid value provided for status"
          }
        ]
      }
      ```

      ### HTTP status code summary
      HTTP Code                          | Description
      -----------------------------------|------------
      200 - OK                           | Everything worked as expected
      400 - Bad Request                  | The request was unacceptable, often due to missing a required parameter.
      401 - Unauthorized                 | No valid OAuth2 token provided
      404 - Not Found                    | The requested resource doesn't exist
      409 - Conflict                     | The request conflicts with another request (perhaps due the resource was updated)
      429 - Too Many Requests            | Too many requests hit the API too quickly. We recommend an expontential backoff of your requests.
      500, 502, 503, 504 - Server Errors | Something went wrong on Brave New Coin's end. (These will be rare).

      ### Handling Errors
      Our API libraries raise exceptions for many reasons, such as invalid parameters, authentication errors, and network unavailability. We recommend writing code that gracefully handles all possible API exceptions.
    x-traitTag: true
  - name: Pagination
    description: |
      All top-level API resources have support for bulk fetches via "list" API methods. For instance, you can list assets, list exchange tickers, and list index tickers. These list API methods share a common structure, taking at least these three parameters: `size`, `timestamp` or `startAfter`.

      Brave New Coin API's utilise cursor-based pagination using the `startAfter` parameter. The parameter should be an existing object ID and returns resources in reverse chronological order. The `startAfter` parameter returns resources listed after the named resource. For APIs which take both a `startAfter` and `timestamp` parameters, the `timestamp` is ignored if `startAfter` is provided.

      Arguments     |                         | Description
      --------------|-------------------------|------------
      size          | Optional, default is 10 | The number of resources to be returned, between 1 and 2000.
      startAfter    |                         | A cursor for use in pagination. startAfter is an resource ID that defines your place in the list.
      timestamp     |                         | The timestamp to start searching from going backwards in time.

      List Response Format | Description
      ---------------------|------------
      content              | An array containing the actual response elements, paginated by any request parameters.
      nextId               | The value to be provided in the `startAfter` to get the next page.

  - name: Timezones
    description: |
      Brave New Coin APIs will return datetime values in ISO8601 format. Datetime values are always returned in UTC time (as indicated by the `Z` at the end of the datetime value).

      Currently Brave New Coin APIs only accept datetimes in query parameters and request bodies which are in UTC.
  - name: Versioning
    description: |
      When we make backwards-incompatible changes to the API, we will release a new version. The current version is **v3**, for more information regarding changes see the [API changelog](#tag/Versioning)

      The following changes are considered backwards-compatible:
        * Adding new API resources
        * Adding new optional request parameters to existing API methods
        * Adding new properties to existing API responses
        * Changing the order of properties in existing API responses
        * Changing the length or format of object IDs or other opaque strings
    x-traitTag: true
  - name: Asset
    description: Retrieve information about assets.
  - name: Market
    description: Retrieve information about markets.
  - name: Exchange
    description: Retrieve information about exchanges.
  - name: Exchange Ticker
    description: Retrieve the exchange ticker information.
  - name: Market Weighted Averages
    description: Retrieve the market weighted averages.
  - name: Global Weighted Averages
    description: Retrieve the global weighted averages.
  - name: Open, High, Low, Close, Volumes
    description: Retrieve the open high low close volumes.
  - name: Market Capitalisation
    description: Retrieve the market capitalisation.
  - name: Rates
    description: Retrieve the exchange rates between assets.
paths:
  /oauth/token:
    post:
      tags:
        - Authentication
      summary: Client Credentials
      description: |
        This is the OAuth 2.0 grant that server processes utilize in order to access an API.
        Use this endpoint to directly request an Access Token by using the Client Credentials (a Client ID and a Client Secret).

        The BNC authentication endpoint is https://api.bravenewcoin.com/v3/oauth/token
      operationId: clientCredentials
  /asset:
    get:
      tags:
        - Asset
      summary: List all assets
      security:
        - auth:
            - read:asset
      description: List all assets or provide a query parameter to search.
      operationId: listAssets
  '/asset/{id}':
    get:
      tags:
        - Asset
      summary: Retrieve an asset
      security:
        - auth:
            - read:asset
      description: Retrieves the details of an asset that has previously been created. Supply the unique identifier of the asset.
      operationId: getAssetById
  /market:
    get:
      tags:
        - Market
      summary: List all markets
      security:
        - auth:
            - read:market
      description: List all markets or provide a query parameter to search.
      operationId: listMarkets
  '/market/{id}':
    get:
      tags:
        - Market
      summary: Retrieve a market
      security:
        - auth:
            - read:market
      description: Retrieves the details of a market that has previously been created. Supply the unique identifier of the market.
      operationId: getMarketById
  /exchange:
    get:
      tags:
        - Exchange
      summary: List all exchanges
      security:
        - auth:
            - read:exchange
      description: List all exchanges or provide a query parameter to search.
      operationId: listExchanges
  '/exchange/{id}':
    get:
      tags:
        - Exchange
      summary: Retrieve an exchange
      security:
        - auth:
            - read:exchange
      description: Retrieves the details of an exchange that has previously been created. Supply the unique identifier of the exchange.
      operationId: getExchangeById
  /exchange-ticker:
    get:
      tags:
        - Exchange Ticker
      summary: List all exchange tickers
      security:
        - auth:
            - read:exchange-ticker
      description: |-
        This API provides ticker information by exchange and market. If no timestamp is provided, then only the most recent ticks will be provided.

        Using this API by **base and quote symbol is not recommended** as it may result in an error when duplicate symbols are found. Searching by marketId is recommended and will result in a faster response.
      operationId: listExchangeTicker
  /index-ticker:
    get:
      tags:
        - Index Ticker
      summary: Get all the index tickers
      security:
        - auth:
            - read:index-ticker
      description: |
        This API provides support to get the index tickers. The API allows getting ticks for all the indices. Type parameter can be used
        to filter the type of index being returned.

        Currently the following types of indices are supported -

        | Index Type  | Description                  |
        | ------------|:----------------------------:|
        | MWA         | The Market weighted averages |
        | GWA         | The Global weighted averages |

        Each index type will have an index id which identifies the constituent type used to build the index -

        | Index Type | Index Id  | Output |
        | -----------|:---------:|:---------:|
        | MWA        | Market Id | Average of all tickers for that market |
        | GWA        | Asset Id  | Average of all tickers for that coin / asset |

        Clients are supposed to use this ID to call the other rest API's to get more information about the constituents
        used while building the index.

      operationId: getIndexTicker
  /ohlcv:
    get:
      tags:
        - Open, High, Low, Close, Volumes
      summary: Get end of day Open, High, Low, Close, Volumes
      security:
        - auth:
            - read:ohlcv
      description: |
        Get end of day open, high, low, close and volumes (OHLCV) of market weighted averages or global weighted averages. The 24hr period for end of day is 00:00:00 UTC.

        This API provides the open, high, low, close and volume using the index type provided. If no timestamp is provided, then only the latest averages are returned.

        Currently the following types of indices are supported -

        | Index Type  | Description                  |
        | ------------|:----------------------------:|
        | MWA         | The Market weighted averages |
        | GWA         | The Global weighted averages |

        Each index type will have an index id which identifies the constituent type used to build the index -

        | Index Type | Index Id  | Output |
        | -----------|:---------:|:---------:|
        | MWA        | Market Id | Average of all tickers for that market |
        | GWA        | Asset Id  | Average of all tickers for that coin / asset |
      operationId: listOhlcv
  /market-cap:
    get:
      tags:
        - Market Cap
      summary: |
        List the market capitalisation for assets
      security:
        - auth:
            - read:market-cap
      description: |

        This API will return a list of assets ranked by their market capitalization.

        The Market Cap is calculated based on the free float (or circulating) supply figures and the GWA index price. The Total Market Cap is calculated based on the total supply and the GWA index price.

        If the percentChange parameter is set to true this API will also return movement in percentage of these values over a 24h, 7d or 30d period.

      operationId: listMarketCaps
  /price:
    get:
      tags:
        - Rates
      summary: List all prices for a particular asset
      description: |
        ** THIS ENDPOINT IS CURRENTLY NOT AVAILABLE **

        Provides the ability to get the price of a specific asset in all other assets.
      operationId: listAssetPrice
  /convert:
    get:
      tags:
        - Rates
      summary: Convert the value of one asset into another asset
      description: |
        ** THIS ENDPOINT IS CURRENTLY NOT AVAILABLE **

        Provides the ability to convert one asset into another asset.
      operationId: convertAsset
  /rates:
    get:
      tags:
        - Rates
      summary: Convert the value of one asset into another asset
      description: |
        ** THIS ENDPOINT IS CURRENTLY NOT AVAILABLE **

        Provides the ability to convert one asset into another asset.
      operationId: getExchangeRates
  /taxonomy/general:
    get:
      tags:
        - Taxonomy
      operationId: getTaxonomyGenerals
      summary: Get a restricted subset of taxonomy data for all assets
      security:
      - auth: ['read:taxonomy-general']
  '/taxonomy/general/{id}':
    get:
      tags:
        - Taxonomy
      operationId: getTaxonomyGeneral
      summary: Get a restricted subset of taxonomy data for specific assets
      security:
      - auth: ['read:taxonomy-general']
  /taxonomy/asset:
    get:
      tags:
        - Taxonomy
      summary: Get all the taxonomy fields for all the assets
      operationId: getTaxonomyAssets
      security:
      - auth: ['read:taxonomy-asset']
  '/taxonomy/asset/{id}':
    get:
      operationId: getTaxonomyAsset
      tags:
        - Taxonomy
      summary: Get all the taxonomy fields for specific assets
      security:
      - auth: ['read:taxonomy-asset']
  /taxonomy/social:
    get:
      operationId: getTaxonomySocials
      tags:
        - Taxonomy
      summary: Get all the social data for the current day available for all assets.
      security:
      - auth: ['read:taxonomy-social']
  '/taxonomy/social/{id}':
    get:
      operationId: getTaxonomySocial
      tags:
        - Taxonomy
      summary: Get all the social data for the current day for specific assets.
      security:
      - auth: ['read:taxonomy-social']
  /taxonomy/filter:
    get:
      tags:
        - Taxonomy
      summary: Get all the taxonomy fields that are useful for filtering for all the assets
      operationId: getTaxonomyFilters
      security:
      - auth: ['read:taxonomy-filters']
  '/taxonomy/filter/{id}':
    get:
      tags:
        - Taxonomy
      summary: Get all the taxonomy fields that are useful for filtering for specific assets
      operationId: getTaxonomyFilter
      security:
      - auth: ['read:taxonomy-filters']
